### ISSUE TITLE
Exscript does not return full output

### ISSUE THREAD

**Issue by armartirosyan** [knipknap/exscript#150]
I have a simple script (below) which should return an output from a simple show command but instead I am getting the one line of the output or no output at all.

```
>>> from Exscript.protocols import *

>>> conn = SSH2()
>>> conn.connect("192.168.0.1")
>>> conn.login(Account("username", "password"))
>>> conn.send("\r")
>>> conn.response
u'--- JUNOS 13.2R7.5 built 2015-02-12 11:55:28 UTC'
>>> conn.execute("\r")
(0, <_sre.SRE_Match object at 0x7f6bd4707440>)
>>> conn.response
u''
>>> conn.execute("show version")
(0, <_sre.SRE_Match object at 0x7f6bd4707440>)
>>> conn.response
u'\r\n\r\n{master}\r\username@S1> '
```

Any help is greatly appreciated!

**Comment by knipknap** [comment]
The reason is your use of conn.send(). send() does not wait for a prompt before returning, which means that, depending on timing, the prompt will be received during the execution of your first "conn.execute()", or, if you are unlucky, during any of the following commands.
http://exscript.readthedocs.io/en/latest/Exscript.protocols.html#Exscript.protocols.Protocol.send

In addition, you are using "conn.execute('\r')", which means that you are effectively sending TWO newlines:
http://exscript.readthedocs.io/en/latest/Exscript.protocols.html#Exscript.protocols.Protocol.execute

This again means that the device will respond with two prompts - creating the same timeing related problem. So you should be using "conn.execute('')" without sending the extra newline.

Please make sure that you read this carefully:
http://exscript.readthedocs.io/en/latest/trouble.html

The problems described there are closely related to what is happening in your specific example.
