### ISSUE TITLE
_authentication_reconnect_hack issue on some devices

### ISSUE THREAD

**Issue by maximumG** [knipknap/exscript#166]
The re-connection hack created for JunOS is causing some issue on some other vendor SSH implementation we have in the fields.

https://github.com/knipknap/exscript/blob/e5b29b91fb4bd65cce68e059daa2115cd07e0646/Exscript/protocols/ssh2.py#L62

Is it possible to add a new attribute to the SSH2 class that will replace this module variable ? The idea is being able to specify whether or not we want a disconnection after each attempt (default: True)

I would be able to create a pull requests if you want.

**Comment by knipknap** [comment]
I think the right fix may be to make this an attribute of the driver, like `Driver.reconnect_between_auth_methods`, and that should default to False, and be set to True only in the JunOS ERX driver.

The problem is that this requires the driver to be selected before the authentication is complete. But this may actually already be possible with SSH, because we are already using self.client.get_banner() to find the driver as early as possible.

So I guess it is as simple as:

1. Make sure that JunOS ERX returns something useful when using `SSH.get_remote_version()`
2. Implement `JunOSERXDriver.check_response_for_os()`, like IOSXRDriver does.
3. Add `Driver.reconnect_between_auth_methods = False`
4. Add `JunOSERXDriver.reconnect_between_auth_methods = True
5. Replace the hack in ssh2.py by looking at the driver attribute instead.

**Comment by maximumG** [comment]
Thanks for the reply. I admit your way is much more scalable than mine 👍 .

I would have appreciate to take care of this issue (it took me almost 1 work day to understand that our device does not support to much re-connection...), but I do not have any JunOS ERX device to work with.

Until someone is able to test this (a simple `ssh username@junos -vvvv` gives some hint a remote version in the debug output before authentication), I will monkey patch the code on my side to work with our devices.

**Comment by knipknap** [comment]
Ok, I'll see if I can find someone to provide with info on what `get_remote_version()` does on ERX.

**Comment by knipknap** [comment]
Sadly my contact didn't have any such devices... what would make sense is to implement all of the above except for the changes an the ERX driver. That way the hack wouldn't actually be used, but it could easily be enabled if someone runs into a device that requires re-connection.

**Comment by maximumG** [comment]
Thanks for you quick support and response. I will try to get a pull request to correct this issue and implement everything we discussed ASAP.

**Comment by knipknap** [comment]
We found the device that has a problem without the reconnect_hack. It is running IOS 15.2.

@maximumG Can you tell me the OS of the device that tripped when using the hack? I want to make sure that it's safe to re-add the hack, but only in the IOSDriver.

**Comment by knipknap** [comment]
@bigmars86 added the hack for IOS for now, see commits de07949dcd24f2e50748f796651ea67aea690bac and cefa11c4c85d063129638492668bb29373b9ad47. Please re-open if this causes any problems.

**Comment by maximumG** [comment]
I needed to remove this hack for Icotera based driver. So it was safe to add it on IOS 15.2.
