### ISSUE TITLE
How to disable the auto enable feature?

### ISSUE THREAD

**Issue by renard** [knipknap/exscript#62]
Hi

Thanks for `exscript` this is pretty good for automation.

Meanwhile I try to dump the configuration of a brocade switch. My user has administrator privileges thus I do not need to run `enable`. I cannot find a way to disable the auto enable feature:

````
All jobs enqueued.
Waiting for the queue to finish.
SSH@sw1-p1#enable
Invalid input -> enable
Type ? for a list
SSH@sw1-p1#sw1-p1.example.com error: Login failed
Traceback (most recent call last):
````

This works fine if I disable the call `self.auto_app_authorize(app_account, flush = flush)` in `Protocol.py`  (line 597).

This is not a fine solution since it implies modifying the upstream.

Thanks for your support.

Cheers.

**Comment by egroeper** [comment]
I think adding a parameter "only_authenticate" to the start and quickstart helper methods is the right way to go.
Of course then a decorator autoauthenticate() is needed.

**Comment by renard** [comment]
@egroeper I use the Exscript API to run my own rancid-like software in less than 500 lines of code!
I have abilities to use (or don't use) the auto authenticate feature.

Check it out https://github.com/renard/cidr

**Comment by egroeper** [comment]
@renard No. You don't use the auto_authorize(!) feature. You are simply handling that functionality yourself in cidr. But as I see: Since authorizing (or not) is device specific in your code, my pr doesn't help in cidr.
My pr helps, if your devices are configured identically regarding the need to authorize.

Please write, if you think exscript should have a device/host specific setting.
For my personal needs the above pr is enough.

**Comment by renard** [comment]
My experience is that auto authorizing must be device independent since you don't know which require authorization and which do not.

OTOH it really depends on device configuration. For example on Cisco device you can give a admin privilege on login then you won't be able to send the "enable" command, or you can give user privilege with or without the ability to send the "enable" command.

**Comment by egroeper** [comment]
>For example on Cisco device you can give a admin
>privilege on login then you won't be able to send the "enable" command, or you can give user
>privilege with or without the ability to send the "enable" command.

I thought this was the problem here? For exscript the default is a separate authorization, if the device supports it (driver implements auto_authorize).
With my change you can avoid that (if you know your user has admin privilege or isn't allowed to call enable) and continue using (quick-)start helper methods or simply use the new decorator autoauthenticate. Of course it's up to your script to use exscript accordingly. You are always free to only use the lower level methods.

**Comment by taewookim** [comment]
is there a way to login to telnet w/o authentication? (i.e. skip it if not asked)
