### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by sbraz** [knipknap/exscript#73]
Hi, do you plan on making the module Python3-compatible?

**Comment by egroeper** [comment]
I currently have no specific plans to port exscript to Python 3 and I don't think @knipknap has either.
Of course I would be happy to merge a pull request if somebody (you?) does the porting.
I have to admit, I don't know how much effort is needed.

I currently have no plans to abandon exscript and I use it myself for work. So sooner or later a Python 3 port needs to be done.
As the underflying paramiko SSH library has a Python 3 compatible version since last year, I currently don't see a showstopper for porting exscript.

**Comment by sbraz** [comment]
Well I think running ```2to3``` would make it work with Python 3 but I don't really know how to handle/test compatibility with Python 2, especially older versions.
I think handling both versions is where the most effort is required.

**Comment by egroeper** [comment]
I don't think its feasible to drop Python 2 support yet.
We would need to support Python 2.6+ (or just 2.7?) for a while.

**Comment by alexkross** [comment]
For Python 3 port try my recent (https://github.com/alexkross/exscript) fork.
Note that tests and demos are just passed through 2to3, need checking out.

Some part of code (Queue and workqueue/* modules, exscript scripts) were to be made to work on Windows platform. Still undone and deferred, due to massive passing (pickle/unpicke) of unpickable objects on multiprocessing (spawn method). Trying to fix that was hard, because such objects are difficult to locate and they might come from exscript's script as a python code.

**Comment by egroeper** [comment]
@alexkross Sorry for the delay and thanks for your contribution. I will have a look at it soon.

**Comment by egroeper** [comment]
I just now merged your commits into the new feature branch [python3](https://github.com/knipknap/exscript/tree/python3). I fixed the author of your commits and hope it's okay.
Since your commits are fairly big, it will take me some time reviewing them.

**Comment by egroeper** [comment]
Tests are not working on Python 3.4, yet.

**Comment by alexkross** [comment]
-------- Original Message --------
> Tests are not working on Python 3.4, yet.
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/knipknap/exscript/issues/73#issuecomment-91897012>.
>

I am out of my office for the next week. So I'll check later.

**Comment by alexkross** [comment]
As to the tests that are not working, I see too many fixes to be done. It
is not only because of Python 3 incompatibility, but mostly because Windows
platform incompatibility that I have to use exscript on as a common
environment with my coworkers.

Windows also completely broke multiprocessing, so exscript scripting
feature (more on this here:
https://github.com/knipknap/exscript/issues/73#issuecomment-88512194).

Ported to Python 3 exscript API work fine for my cases.

However tests are essential. I see the only possibility for me to port only
subset of the tests that cover the core API.
Another deferred alternative is to drop Windows compatibility on that
branch. Sorry.

Best regards.

On Sat, Apr 11, 2015 at 11:10 PM, alexander.kross <alexander.kross@gmail.com

**Comment by egroeper** [comment]
My goal is to have a one branch / version, that supports Pyhton 2 and 3. I don't want to manage separate branches.
I will see, if I'm able to accomplish this. But I won't have time for this in the near future.

**Comment by egroeper** [comment]
Ubuntu is going to make (did already?) Python3 the default. Python2 will then not be preinstalled anymore:
https://wiki.ubuntu.com/Python/3

Just another reason...

**Comment by egroeper** [comment]
I'm currently thinking about using a python-futurize approach and support only python 2.7 and 3.3+ in the future. Is there anyone out there who still needs Python 2.6 (isn't it unsupported now?) or Python 3.0 - 3.2?

That way we would have a single branch supporting both Python versions and it will be easier to drop Python 2 support somewhere in the future.

Doing this port myself will help me to get in touch with exscript codebase.

**Comment by egroeper** [comment]
@knipknap Of course I'm especially interested in your input.

**Comment by knipknap** [comment]
Hi Enno, I agree that Python 2.6 needs no longer to be supported. Even the
most conservative setups should use 2.7 by now.

As for Python 3.0-3.2, it was never supported to begin with. So no reason
to add support now.

-Samuel

**Comment by knipknap** [comment]
I just removed a lot of code (commits 8a9d5a8506af41060471e7d69dbcdbcd4b31e5b3 and a712d3ac1825a8c6bc7f409e2b964db08c355bc7), so the porting effort should be somewhat easier. (I am probably not going to find the time to port it soon, however.)

**Comment by knipknap** [comment]
Ugh, I have tried to re-base @egroeper's python3 branch on 0e7adffacec69dabec99d72cebef9e36fd72af6a (because that is the point after which I changed the directory layout in master), but that fails:

The python3 branch has a commit that converts all test files to Windows-style newlines, resulting in every single line being in conflict with master.
If anyone has an idea how to rebase this, I would be happy to begin the transition the Python 3...

**Comment by egroeper** [comment]
Please don't waste time with the Python3 branch. I don't think it's the right way to do this port.
I started a new effort last year, but didn't finish it.

Of course this means to waste the work of @alexkross, but in my opinion it's nevertheless the right way to go.

I just pushed my work to new_python3. So You  can decide, if you want to continue there or start a new approach by yourself.

I documented my ideas above. I first tried to make this run with Python 3 and wanted to reestablish Python 2 support after that. Don't know anymore where I read about this approach. But last year I thought this would be the right way to go.
Unfortunately I gave up on deciding where unicode and where binary string are right. This low-level stuff is pretty hard to me. You should probably have a look at paramikos solution here.

**Comment by knipknap** [comment]
Ah, Thanks, Enno. I agree with your approach. I think the boundary for unicode should be the Protocol class; the underlying libraries (paramiko and telnetlib) would still be using bytes. That is a similar approach to what paramiko is doing: Their transport and channels are using bytes, while their client (which we are not using) is using str.

To start the transition, I have re-based your branch on 0e7adff and pushed it as python3_knipknap first.

Second, after looking through your commits, it seems that up until 53a486532817a21b18d7ef4ac635dea1454f5ce0 your changes are fully backward compatible, so I have merged them into master right away (c6e93d5126fe79c0f7a5c2e5c0244e42b539f862).

Since your branch also contains several other non-breaking compatible commits later, I will try to cherry-pick them next.

**Comment by knipknap** [comment]
All non-breaking changes from @egroeper's `new_python3` are now merged into master.

I have also created a `py3` branch that is essentially @egroeper's `new_python3` rebased against master. So if anyone feels like continuing the effort, the `py3` branch is where we're at. Any other python3 branches are obsolete.

**Comment by alexkross** [comment]
Thank you, Enno and Samuel, for your effort to port the code to Python 3! I
very appreciate this movement.
Unfortunately I'm currently involved in deployment of a Cisco ACI DC pod,
and that beast uses REST API a lot.
So I cannot anticipate how soon I will try the new version.
Thank you nevertheless.

**Comment by 1001QAdotNET** [comment]
Can anybody help with instructions to install this for Python 3.5 x32 running on Windows?
I think that the usual way (pip install exscript) attempts to install the wrong version

Collecting exscript
  Using cached Exscript-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\MyUser\AppData\Local\Temp\pip-build-pe80jvo3\exscript\setup.py", line 4, in <module>
        from Exscript.version import __version__
      File "C:\Users\MyUser\AppData\Local\Temp\pip-build-pe80jvo3\exscript\Exscript\__init__.py", line 34, in <module>
        from Exscript.Queue       import Queue
      File "C:\Users\MyUser\AppData\Local\Temp\pip-build-pe80jvo3\exscript\Exscript\Queue.py", line 35, in <module>
        from Exscript.Logger import logger_registry
      File "C:\Users\MyUserA\AppData\Local\Temp\pip-build-pe80jvo3\exscript\Exscript\Logger.py", line 27, in <module>
        from itertools import chain, ifilter
    ImportError: cannot import name 'ifilter'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\MyUser\AppData\Local\Temp\pip-build-pe80jvo3\exscript\

**Comment by knipknap** [comment]
Python 3 support is not completed yet, though I estimate that master is 90% there.

**Comment by 1001QAdotNET** [comment]
Thanks for the update. please if you complete this update the PyPi package description to reflect this compatibility

**Comment by knipknap** [comment]
All but one test now pass on Python 3 with the changes landed in master. The remaining bug appears to be harder to track down - if anyone has a use case that fails with a traceback, please let me know.

**Comment by knipknap** [comment]
Python 3 support is now complete, all tests passed on my machine.
(I am not going to make a release on PyPi before anyone has tested this in practice.)

**Comment by 1001QAdotNET** [comment]
I am willing to give it a try but I might not be able to install in from sources on a Windows machine. Can you provide a wheel file ?

**Comment by 1001QAdotNET** [comment]
Note: I found your libraries net superior to netmiko and I would love to be able to work with it under Python 3.x

**Comment by iassis** [comment]
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "C:\Users\IGOR~1.ASS\AppData\Local\Temp\pip-kz6f208i-build\setup.py",
>  line 4, in <module>
>         from Exscript.version import __version__
>       File "C:\Users\IGOR~1.ASS\AppData\Local\Temp\pip-kz6f208i-build\Exscript\_
> _init__.py", line 34, in <module>
>         from .queue import Queue
>       File "C:\Users\IGOR~1.ASS\AppData\Local\Temp\pip-kz6f208i-build\Exscript\q
> ueue.py", line 40, in <module>
>         from .util.decorator import get_label
>       File "C:\Users\IGOR~1.ASS\AppData\Local\Temp\pip-kz6f208i-build\Exscript\u
> til\decorator.py", line 28, in <module>
>         from ..protocols.exception import LoginFailure
>       File "C:\Users\IGOR~1.ASS\AppData\Local\Temp\pip-kz6f208i-build\Exscript\p
> rotocols\__init__.py", line 27, in <module>
>         from .protocol import Protocol
>       File "C:\Users\IGOR~1.ASS\AppData\Local\Temp\pip-kz6f208i-build\Exscript\p
> rotocols\protocol.py", line 41, in <module>
>         from ..util.crypt import otp
>       File "C:\Users\IGOR~1.ASS\AppData\Local\Temp\pip-kz6f208i-build\Exscript\u
> til\crypt.py", line 34, in <module>
>         from Crypto.Hash import MD4
>     ImportError: No module named 'Crypto'
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\IGOR~1.A
> SS\AppData\Local\Temp\pip-kz6f208i-build\

I'm still getting this type of thing on Windows when trying to install the current master.

**Comment by 1001QAdotNET** [comment]
Is this for Python 3?

**Comment by knipknap** [comment]
This looks like the dependencies were not installed, it is missing pycrypto, though that is listed as a requirement.

**Comment by knipknap** [comment]
I have uploaded a .whl of the current master branch here:

https://www.file-upload.net/download-12419227/Exscript-2.3.66-py2.py3-none-any.whl.html

Since I do not trust the file hoster, please check the MD5sum before installing:

```
$ md5sum dist/Exscript-2.3.66-py2.py3-none-any.whl
23ad3533f5f318d90d2fc3b1a066bb0b  dist/Exscript-2.3.66-py2.py3-none-any.whl
```

I expect this to be unstable for Py3, though Py2 appears to be working fine for us.

**Comment by 1001QAdotNET** [comment]
Thanks a lot. 
I will test it some time this week, I am very interested in moving to Exscript for Python 3.x since I have other dependencies on this package. I will get back here with more details after I migrate my scripts to this and after I start testing it
