### ISSUE TITLE
IOS driver issue

### ISSUE THREAD

**Issue by maximumG** [knipknap/exscript#78]
Hello,

Thanks for this great module. Really helps in doing my job at work :-).
I'm facing an issue concerning the *driver auto discovery* feature : 

* When connecting to any Cisco device (switch, router), The OneOS driver is used. After investigating it seems that both manufacturer are using the same CLI concept. This is working great on all Cisco device even if this might be "dirty".
* **When connecting to Cisco NX OS devices, The OneOS driver is not used even if its the same CLI concept as IOS.**

The issue is especially on the *_first_prompt_re* regex

```python
_first_prompt_re = re.compile(r'\r?\n\r?\n[\-\w+\.]+[>#]$')
```
This regex matches the banner followed by 2 CRLF. However on Nexus only 1 CRLF is present  between the banner and the prompt.

Hope it would be possible for the author to modify the regex above to something like that :-)

```python
_first_prompt_re = re.compile(r'\r?\n?\r?\n[\-\w+\.]+[>#]$')
```

**Comment by egroeper** [comment]
I'm not sure, if I understand you correctly.
You like to use the OneOS driver on your Cisco devices (where normally ios driver should be used).
But on your Cisco NX OS devices the "bug" doesn't work and some other driver (which?) gets selected instead of the OneOS driver?
Does the ios driver not work for you? 
Do you use tacacs?
Can you provide a banner file for your devices (NX OS and other Cisco)? I would like to know, why the ios driver doesn't get selected.

If we fix OS guessing, we should fix it "the right way". Improving "wrong guessing" doesn't make sense to me.

If you want to use one driver on all of your devices and you know which driver you want to use, you should consider manually selecting the driver in your script. Have a look at #64.

**Comment by maximumG** [comment]
Hello,

Thanks for the quick reply.
When I connect to a Nexus device, the *generic* driver is used - I guess this mean that no specific driver matched.
When I specify the driver *IOS* manually, this is working great for Nexus devices. 
However I'd like to use the *auto discovery feature* because I'm working on Cisco router/switches & Cisco Wireless LAN Controller.

I'm using TACACS as AAA on all devices, however in our configuration it seems that the **_tacacs_re** regex is not matched.

Here is a banned from NXOS (all kind of version)

```
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2002-2009, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php
hostname#

```

As you can see the prompt is directly attached to the banner meaning no empty line to seperate.

Maybe I can run Exscript in debug mode to see what are the prompt received when authenticating. Do you think this could help ?

**Comment by egroeper** [comment]
Looking at [Cisco IOS NX-OS comparison](http://docwiki.cisco.com/wiki/Cisco_NX-OS/IOS_Configuration_Fundamentals_Comparison) I think it would be better to have a separate driver for nx-os. Especially because NX-OS doesn't need/have an auto_authorize (enable) feature.
It would be great, if you could write that driver.

As your NX-OS devices aren't detected as neither IOS nor OneOS, writing a separate driver should be no problem (with os guessing).
You should try to write a driver for NX-OS based on the ios driver. There you need to adjust the regexes, os guessing (check_head_for_os) and remove the auto_authorize method. It's no rocket science.

I will try to help you with that, if needed.
We need a banner (copy of complete login procedure shell output) for testing.
Have a look at [existing banners (ios.1, ...)](https://github.com/knipknap/exscript/tree/master/tests/Exscript/protocols/banners).

Debugging is easy:

    import Exscript
    from Exscript.util.interact import read_login
    
    account = read_login()
    conn = Exscript.protocols.SSH2(debug = 1)
    host = 'your host goes here'

    conn.connect(host)
    conn.login(account)

**Comment by maximumG** [comment]
Thanks for the answer. I will write this driver this weekend. However do you have any documentation on how to make unittest for Exscript ?

**Comment by egroeper** [comment]
To my knowledge for drivers it should be enough to place one or more matching banner files into the banner directory.
I'm not aware of any more specific tests for the other drivers.

**Comment by egroeper** [comment]
Seems like you fixed it yourself.

Thanks. :-)
